dist: xenial
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3
            - python3-pip
            - python3-setuptools
            - g++-7
      env:
        - WXWIDGETS_VERSION=3.1.1
        - BUILD_TYPE=Release
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3
            - python3-pip
            - python3-setuptools
            - g++-8
      env:
        - WXWIDGETS_VERSION=3.1.1
        - BUILD_TYPE=Release
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3
            - python3-pip
            - python3-setuptools
            - g++-7
      env:
        - WXWIDGETS_VERSION=3.1.2
        - BUILD_TYPE=Release
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3
            - python3-pip
            - python3-setuptools
            - g++-8
      env:
        - WXWIDGETS_VERSION=3.1.2
        - BUILD_TYPE=Release
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3
            - python3-pip
            - python3-setuptools
            - g++-7
      env:
        - WXWIDGETS_VERSION=3.1.1
        - BUILD_TYPE=Debug
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3
            - python3-pip
            - python3-setuptools
            - g++-8
      env:
        - WXWIDGETS_VERSION=3.1.1
        - BUILD_TYPE=Debug
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3
            - python3-pip
            - python3-setuptools
            - g++-7
      env:
        - WXWIDGETS_VERSION=3.1.2
        - BUILD_TYPE=Debug
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3
            - python3-pip
            - python3-setuptools
            - g++-8
      env:
        - WXWIDGETS_VERSION=3.1.2
        - BUILD_TYPE=Debug
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - sudo pip3 install conan
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWXWIDGETS_VERSION=$WXWIDGETS_VERSION ..
  - cmake --build . --config $BUILD_TYPE
  - ./bin/WxTest
